### ISSUE TITLE
Stop using path.join to manipulate URL

### ISSUE THREAD

**Issue by CatChen** [avocadotoastlive/avocadotoast.live#149]
It doesn't work on Windows. `path.join` sees `/...` and treats it as `C:\...`. The output won't be valid URL. Use the `URL` class's `new URL(path, base)` instead.

Read the following MDN document to learn about how to use `new URL(path, base)` as a way to concatenate path: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

Look into this file and find all the `path.join` and `path.resolve` calls: https://github.com/avocadotoastlive/avocadotoast.live/blob/master/_data/data.js. Not all of them need to be corrected. Only those dealing with "virtual path" need to be updated. (Virtual path means a path used in URL instead of local file system.)

`url.resolve` could be a good replacement here, but it's deprecated. Here's how to use `URL` class to implement the `url.resolve` function: https://nodejs.org/api/url.html#url_url_resolve_from_to

**Comment by Bittttter** [comment]
@CatChen Please review it if you have time ~ And then I will improve it.

**Comment by CatChen** [comment]
@Bittttter If you don't mind, I would make the changes myself and merge #163.

**Comment by CatChen** [comment]
@Bittttter I merged it. Thank you for your contribution!

**Comment by Bittttter** [comment]
@CatChen Sorry to disturb you. I didn't notice the mention..:joy:
